# FinMind API Token
# 為了您的帳戶安全，請將此金鑰視為密碼，不要分享給他人或上傳到公開的程式碼倉庫。
FINMIND_API_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRlIjoiMjAyNS0wOS0xNyAxMDo0MDo1OSIsInVzZXJfaWQiOiJhbHZpbmh1YW5nIiwiaXAiOiIxMTguMjMyLjExNS4yNDMifQ.Sr49HaiKSmbG6C8OENiyN8WhLDvvBrfC5exjmGapwSg"
